config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to:  'static_pages#about'
  get '/help', to:  'static_pages#help'
  get '/contact', to:  'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length:{maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length:{minimum: 6}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title= '')
    base_title = "Ruby on Rails Tutorial Sample app"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "アバウト" , about_path %></li>
      <li><%= link_to "お問い合わせ" , contact_path%></li>
    </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "つぶやきアプリ" , root_path , id:"logo"%>
    <nav>
      <ul class = "nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "ヘルプ", help_path%></li>
        <li><%= link_to "ログイン", '#'%></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim'%>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'アバウト')%>
  <h1>つぶやきアプリについて</h1>
  <p>つぶやきアプリとは
  <a href="https://railstutorial.jp/">Rails Tutorial</a>
  を参照してつくったアプリです。
  </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'コンタクト')%>
  <h1>お問い合わせ</h1>
  <p>何かあれば
  <a href="https://railstutorial.jp/">Rails Tutorial</a>
  まで尋ねてください。
  </p>

app/views/static_pages/help.html.erb
<% provide(:title, 'ヘルプ')%>
  <h1>お助けページ</h1>
  <p>わからないことは
  <a href="https://railstutorial.jp/">Rails Tutorial</a>
  を確認してください。
  </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>つぶやきアプリ</h1>
  <h2>つぶやきアプリへようこそ！こちらは
    <a href="https://railstutorial.jp/">Rails Tutorial</a>
    を参考にしています。
    <h2>

      <%= link_to "新規登録はこちら！" , signup_path , class: "btn btn-lg btn-primary"%>
</div>

<%= link_to image_tag("rails.png" , alt:"Rails logo"), 'http://rubyonrails.org/'%>

app/views/users/new.html.erb
<h1>新規登録</h1>
<p>Find me in app/views/users/new.html.erb</p>